initial_number_of_orders: 10000
batch_number_of_orders: 200

input:
  customers: data/generated/customers.csv
  products: data/generated/products.csv


output_directory: data/generated
output_prefix: orders
